---
# 安装
- name: Install SQLServer2012SP4
  win_shell:
    .\{{sqlserver_name}}.exe /q /IACCEPTSQLSERVERLICENSETERMS /ACTION=Install /FEATURES=SQL,AS,RS,IS,Tools /SECURITYMODE=SQL /SQLSYSADMINACCOUNTS="{{ansible_hostname}}\websoft9" /INSTANCENAME=MSSQLSERVER  /SAPWD="websoft9!" /ISSVCSTARTUPTYPE=Automatic /BROWSERSVCSTARTUPTYPE=Automatic /SQLSVCSTARTUPTYPE=Automatic /TCPENABLED=1 /SQLSVCACCOUNT="NT Service\MSSQLSERVER"
  args:
    chdir: C:\temp\

## 快捷方式
- name: Create SSMS lnk
  win_shortcut:
    src: C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\Ssms.exe
    dest: C:\Users\Public\Desktop\SQL Server 2012 Management Studio.lnk
    icon: C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\ssms.ico