---
# 创建临时解压目录
- name: create temporary directory to extract sqlserver
  win_file:
    path: C:\temp\{{sqlserver_name}}

# 解压
- name: unzip {{sqlserver_name}}
  win_shell:
    .\{{sqlserver_name}}.exe /u /x:c:\temp\{{sqlserver_name}}
  args:
    chdir: C:\temp\

# 安装
- name: Install {{sqlserver_name}}
  win_shell:
    c:\temp\{{sqlserver_name}}\setup.exe /Q /IACCEPTSQLSERVERLICENSETERMS /ACTION=install /FEATURES=SQL,AS,RS,IS,Tools /INSTANCENAME=MSSQLSERVER

## 快捷方式
- name: Create SSMS lnk
  win_shortcut:
    src: C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\Ssms.exe
    dest: C:\Users\Public\Desktop\SQL Server 2012 Management Studio.lnk
    icon: C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\ssms.ico